import { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { useTranslation } from "next-i18next";

import styles from "./Home.module.scss";
import { Header } from "../Header";
import { ProduceList } from "../ProduceList";
import { ProduceData } from "../../data/produce";

interface HomeProps {
  produce: ProduceData[];
}

export const Home: NextPage<HomeProps> = ({ produce }) => {
  const { t } = useTranslation(["home", "common"]);
  const [query, setQuery] = useState("");

  const leftPredicate = (p: ProduceData) => {
    return p.isClimacteric || !p.isEthyleneSensitive;
  };
  const rightPredicate = (p: ProduceData) => {
    return !p.isClimacteric || !p.isEthyleneSensitive;
  };

  return (
    <>
      <Head>
        <title>{t("common:siteTitle")}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header onQueryChange={setQuery} />

      <main className={styles.main}>
        <ProduceList
          title={t("climacteric")}
          className={styles.climacteric}
          produce={produce.filter(leftPredicate)}
          query={query}
        />
        <ProduceList
          title={t("nonClimacteric")}
          className={styles["non-climacteric"]}
          produce={produce.filter(rightPredicate)}
          query={query}
        />
      </main>
    </>
  );
};
