import type { NextPage } from "next";
import Head from "next/head";
import styles from "./Home.module.scss";
import { useState } from "react";
import { Footer } from "../Footer";
import { Header } from "../Header";
import { ProduceList } from "../ProduceList";
import { ProduceData } from "../../data/produce";

interface HomeProps {
  produce: ProduceData[];
}

export const Home: NextPage<HomeProps> = ({ produce }) => {
  const [query, setQuery] = useState("");

  return (
    <div className={styles.container}>
      <Head>
        <title>Climactérique</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header onQueryChange={setQuery} />

      <main className={styles.main}>
        <ProduceList
          title="Climacteric"
          className={styles.climacteric}
          produce={(produce ?? []).filter((x) => x.isClimacteric)}
          query={query}
        />
        <ProduceList
          title="Non-Climacteric"
          className={styles["non-climacteric"]}
          produce={(produce ?? []).filter((x) => !x.isClimacteric)}
          query={query}
        />
      </main>

      <Footer />
    </div>
  );
};
