import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.scss";
import { Footer } from "./Footer";
import { Header } from "./Header";
import { ProduceList } from "./ProduceList";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Climactérique</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      
      <main className={styles.main}>
        <ProduceList title="Climacteric" className={styles.climacteric} />
        <ProduceList
          title="Non-Climacteric"
          className={styles["non-climacteric"]}
        />
      </main>

      <Footer />
    </div>
  );
};

export default Home;
