import Head from "next/head";
import { Header } from "../Header";
import { loadProduce, ProduceData } from "../../data/produce";
import styles from "./ProducePage.module.scss";
import { GetStaticProps } from "next";

interface ProducePageProps {
  produce: ProduceData;
  className?: string;
}

export const ProducePage = ({
  className,
  produce,
}: ProducePageProps): JSX.Element => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Climactérique :: {produce.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <section className={`${styles["produce"]} ${className}`}>
        <h2>Produce {produce.name}</h2>
        <p>{produce.type}</p>
      </section>
    </div>
  );
};

export const getStaticPaths = async () => {
  const data = await loadProduce("en");

  const paths = data.map((p) => {
    return {
      params: { id: p.id },
    };
  });

  console.log("fuck", paths);

  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps: GetStaticProps = async (context) => {
  const id = context.params?.id;
  const data = await loadProduce("en");
  const produce = data.find((p) => p.id === id);
  console.log("fuck", id, produce);
  if (!produce) {
    return {
      notFound: true,
    };
  }

  return {
    props: { produce },
  };
};
